# -*- coding: utf-8 -*-
"""byteuprise_task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eIuHe0tojIZqB7q4vD-GT-L_Dq16QWWq
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Titanic-Dataset.csv")
df

df.info()

df.describe()

df.isnull()

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

print(df)

corr_matrix = df.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".3f")

sns.pairplot(df)
plt.show()

