# -*- coding: utf-8 -*-
"""svm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/swapnildahare/f7e728c55a52ea143249d6d99c9d323b/svm.ipynb
"""

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_csv("/content/svm_data.csv")
df

df.info()

plt.hist(df['x1'], bins=10, edgecolor="black")
plt.title("Histogram of age")
plt.show()
